# Generated by Django 3.2.4 on 2021-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='desc',
            field=models.TextField(max_length=5000),
        ),
    ]
